# Site settings
title: Yan Mo
description: 'Business Card Page'
url: 'https://AgentMervin.github.io'
baseurl: ''
profilepic: '/images/homepage.jpeg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '636070888f.js'

author:
  name: 'Yan Mo'
  email: yanmo@usc.edu
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  AgentMervin
  linkedin_username:  mervin-mo

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
